# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_number', models.CharField(max_length=200)),
                ('registration_code', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('students_registered', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('PR', 'Professor'), ('TA', 'TeachingAssistant')], default='PR', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital.Course')),
            ],
        ),
    ]
