# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user_id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vlab_user',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
