# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0002_auto_20160116_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_by', models.IntegerField()),
                ('done_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('action', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='registered_courses',
            name='registered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
