# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vital', '0002_department_securityquestion_userprofile_usersecurityanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLAB_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('admitted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('phone', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='usersecurityanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital.VLAB_User'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
